### ISSUE TITLE
KeyError: 'ethereum' error in logs

### ISSUE THREAD

**Issue by johntdyer** [ThomasPrior/FlexpoolInfo#5]
**Describe the issue**
Seeing this error occasionally in my logs

**To Reproduce**
```
2022-08-31 09:54:31.830 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.flexpoolinfo_0x880668a8c1495d490xxxxxxxxxxx fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 514, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 709, in async_device_update
    raise exc
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 192, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/flexpoolinfo/sensor.py", line 249, in _update
    if len(r5.json()['ethereum']):
KeyError: 'ethereum'
```

**Expected behaviour**
Not throw exceptions :)

**Configuration**

  - platform: flexpoolinfo
    miner_address: "0x880668A8c1495D49xxxxxxxxxxxxxxxsx"
    currency_name: "USD"
    token: ETH

**Environment (please complete the following information):**

 Home Assistant 2022.8.7 
Supervisor 2022.08.5 
Operating System 8.5 
Frontend 20220802.0 - latest

**Comment by ThomasPrior** [comment]
Hey, thanks for logging this.

Just for clarity, it works most of the time, but only occasionally logs an error for this key?

Is any other undesirable behaviour observed with the component?

**Comment by johntdyer** [comment]
Seems to be pretty constant at this point

**Comment by ThomasPrior** [comment]
I'm sorry I need more detail here.

Does it work at all?
If yes, how often do you see these items in your logs?
Do these items in the logs affect functionality?

If this is intermittent in any way, it would suggest the API is returning different data +or at least a different data structure) at different points.

**Comment by ThomasPrior** [comment]
Looking at my dev instance I have two occurrences of this particular error since the 25th of August. The component updates the entity the next time it receives a valid response from the API.
